var xhr = new XMLHttpRequest();
xhr.open("GET", "./js/main.js", true);
xhr.onreadystatechange = () => {
    if (xhr.readyState === XMLHttpRequest.DONE) {
        if (xhr.status === 200) {
            result = xhr.responseText;
            console.log(result);
            fetch("https://cdn.jsdelivr.net/gh/laplamgor/kantai3d-depth-maps@latest/metadata.json").then(
                function (response) {
                    // Called successfully
                    return response.json();
                }).then(function (data) {
                    // patch the main.js and then store it into the storage
                    patchedMainJs = patchMainJs(result, data.patches);
                    // Better performance than using eval
                    var f = Function(patchedMainJs + ";KCS.init();")();
                }).catch(function (err) {
                    // There was an error
                    console.log(err);
                    alert("Unable to load Kantai3D metadata." + err);
                    var f = Function(result)();
                });
        }
    }
};
xhr.send();
function patchMainJs(contents, patches) {
    contents = contents.toString();
    var oldContents = contents;
    var oldlength = contents.length;
    var version = '4.0';
    var error_text = ' - Error occurs! Kantai3D is currently unavailable. Please wait for the developer to update the plugin.';
    var setting_text1 = '120 FPS\\n\\nKantai3D V' + version + '\\n\\nExtra Depth Maps';
    var setting_text2 = 'Extra depth maps are generated by AI \\nfor all CGs without a painted depth map.\\n3D Effects are usually rougher.\\n\\nChanges will be effective on next return \\nto Home Port.';
    for (i = 0; i < window.navigator.languages.length; i++) {
        if (window.navigator.languages[i].startsWith('ja')) {
            error_text = ' - エラーが発生します。 Kantai3D は現在利用できません。 開発者がプラグインを更新するまでお待ちください。';
            setting_text1 = '120 FPS\\n\\nKantai3D V' + version + '\\n\\n追加の深度マップ';
            setting_text2 = '追加の深度マップはAIによって生成され、\\nカスタム手描き深度マップなしでCGに\\nよって使用されます。3D効果の品質は、\\n比較すると粗くなります。\\n\\n変更は、次回母港に戻ったときに有効に\\nなります。';
            break;
        } else if (['zh-HK', 'zh-TW'].indexOf(window.navigator.languages[i]) != -1) {
            error_text = ' - 發生錯誤。 Kantai3D 目前不可用。 請等待開發者更新插件。';
            setting_text1 = '120 FPS\\n\\nKantai3D V' + version + '\\n\\n使用額外深度圖';
            setting_text2 = '額外深度圖由深度學習生成，\\n可以支持未有手繪深度圖的立繪。\\n但立體效果品質普遍較粗糙。\\n\\n變更會在下次返回母港時生效。';
            break;
        } else if (['zh-CN'].indexOf(window.navigator.languages[i]) != -1) {
            error_text = ' - 发生错误。 Kantai3D 目前不可用。 请等待开发者更新插件。';
            setting_text1 = '120 FPS\\n\\nKantai3D V' + version + '\\n\\n使用额外深度图';
            setting_text2 = '额外深度图由深度学习生成，\\n可以支持未有手绘深度图的立绘。\\n但立体效果品质普遍较粗糙。\\n\\n变更会在下次返回母港时生效。';
            break;
        } else if (window.navigator.languages[i].startsWith('en')) {
            break;
        }
    }

    for (const patch of patches) {
        contents = contents.replace(new RegExp(patch.pattern, "gm"), patch.replacement.replace("setting_text1", setting_text1).replace("setting_text2", setting_text2));
        if (contents.length == oldlength) {
            alert(patch.id + error_text);
            return oldContents;
        } else {
            oldlength = contents.length;
        }
    }
    return contents;
}

